### ISSUE TITLE
Delete users

### ISSUE THREAD

**Issue by PeterFleurkens** [Pryx/server-status#22]
We were testing with the site and created some test users but we cannot delete the users anymore. Would be nice if that was possible in the settings

**Comment by Pryx** [comment]
This is intentional - it is possible to disable them though. You can do it by going to their profile and clicking the ✔️ or ❌ symbol next to username to disable or enable the user respectively. Maybe it should just have a better visibility - be turned into a real button for example?

**Comment by PeterFleurkens** [comment]
Yes a real button would be better cause now i would not think of selecting that. But deleting should be a nice option too

**Comment by Pryx** [comment]
I didn't implement deleting users because of archiving purposes - I would have to delete all incidents created by the user or store username separately. And storing username separately could cause trouble when changing the username. But making it look like a button is fast and easy, so it is preferred solution for me :)

**Comment by PeterFleurkens** [comment]
Ah ok clear answer
