### ISSUE TITLE
Cannot move to index page after installation

### ISSUE THREAD

**Issue by carbongtr** [Pryx/server-status#34]
Hello Pryx. Thanks for your script.

I have uploaded your script on on CentOS 7 box with PHP 7 on it. I created the db first and launched the install. it went through without errors but the same installation page gets loaded everytime. i verified in the DB, there are tables which have been created.
I suppose the table will be created by the xxx.sql file.
Can you advise on the way forward plz

**Comment by carbongtr** [comment]
Thanks for the quick reply. Sorry .. im  a newbie on this..
I'll give u the step by step i performed:

1.  downloaded your master file and uploaded to my server (/var/www/html/serverstatus)
2. It has the config.php.template .. should i rename it to config.php ?
3. Created a db serverstatus_db in mysql
4. open browser, launch localhost/serverstatus
5. entered all the details ... click on install
6. installation page loads again.

what am i doing wrong ?

**Comment by Pryx** [comment]
No problem :slightly_smiling_face: 

After step 5 there should be `config.php` file created and `install.sql` and `config.php.template` deleted. If it is not, that would mean that the PHP process doesn't have permission to create and delete files. In this case what you need to do is:

1. Set rw permissions (for example [filezilla](https://bit.ly/2mTPPgR)) - you can set it to 777 for example
2. Delete all tables
3. Rerun installation script
4. Everything should be OK at this point and you can set permissions back as they were (755 or 644 is most commonly used).

That being said you can also do it manually - it's pretty straightforward - you basically just replace `##name##` with website name and so on. Then you rename the `config.php.template` to `config.php` and everything should be up and running. If you opt in for this instead of the script installation, please be sure to delete `install.php` and `install.sql` afterwards.

**Comment by carbongtr** [comment]
Yo! Its working fine..

Thanks Sir !!

**Comment by Pryx** [comment]
Was happy to help 🙂
