### ISSUE TITLE
How to fix lenguage

### ISSUE THREAD

**Issue by darkban** [Pryx/server-status#46]
Hello guys,if I want to correct a few words in my (already existing) language, how can I do? I noticed that editing server-server-status.po status.mo files generates errors
how can this be done?

**Comment by Pryx** [comment]
@darkban the best way is to edit them at [POEditor](https://poeditor.com/join/project/37SpmJtyOm) and then ping me here or at [vojtech@sajdl.com](mailto:vojtech@sajdl.com) and I will push them upstream. Otherwise if you edit server-status.po you need to regenerate server-status.mo file :slightly_smiling_face: But I would really prefer you editing the translation at [POEditor](https://poeditor.com/join/project/37SpmJtyOm) so everyone can have proper translation :wink:

**Comment by Pryx** [comment]
It is but the translations can still be edited AFAIK :slightly_smiling_face:

**Comment by Pryx** [comment]
Fixed in 3d83291
