### ISSUE TITLE
CSS Not Working.

### ISSUE THREAD

**Issue by cattogames** [Pryx/server-status#94]
Hello, I have uploaded all the files and installed it all but the CSS seems to not work 
![image](https://user-images.githubusercontent.com/56136475/71956552-b5a55700-31a8-11ea-87ed-ba3b1d956a9d.png)

**Comment by cattoyt** [comment]
Also after looking the admin panel doesn't exist.. 
![image](https://user-images.githubusercontent.com/56136475/71956817-5a279900-31a9-11ea-9977-aa99d9692c12.png)

**Comment by RobbyTown** [comment]
Because in de install.php there is this line
str_replace("##url##", urlencode($_POST['url']), $config);

Will create in the config file https%3A%2F%2F

This messup the url that you enter by the install

If you download the config.php and edit 2 lines you will fix the error / issue


Please edit 2 lines
define("WEB_URL", "https://status.yoururl.com"); //Used for links 

define("POLICY_URL","https://status.yoururl.com/policy.php");

**Comment by cattoyt** [comment]
Oh, thank you so much

**Comment by Pryx** [comment]
Resolved by #101
